In [1]:
import numpy as np

In [2]:
A = np.array([1, 2])

In [3]:
A

array([1, 2])

In [4]:
A.shape

(2,)

In [5]:
A[0]

1

In [6]:
A[1]

2

## 2次元

In [7]:
B = np.array([[1, 2],
              [3, 4]])

In [8]:
B

array([[1, 2],
       [3, 4]])

In [9]:
B.shape

(2, 2)

In [10]:
B[0]

array([1, 2])

In [11]:
B[0][1]

2

In [12]:
B[:, 0]

array([1, 3])

In [13]:
B[:, 1]

array([2, 4])

In [14]:
B[0, :]

array([1, 2])

In [15]:
B.ravel()

array([1, 2, 3, 4])

## reshape

In [16]:
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [17]:
C.shape

(3, 2)

In [18]:
C.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
C.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [20]:
C.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
C.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
# Error
# C.reshape(5, 3)

## 乱数

In [23]:
y = np.random.rand(20)

y

array([0.50601754, 0.70133878, 0.27110547, 0.20828805, 0.34414086,
       0.00342042, 0.17060389, 0.09541233, 0.60121805, 0.7126341 ,
       0.4207213 , 0.2047374 , 0.79598137, 0.87952454, 0.7683975 ,
       0.42344771, 0.95968593, 0.88164722, 0.26470069, 0.44615204])

## ブールインデックス参照

In [24]:
np.random.seed(0)
y = np.random.rand(20)

y

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [25]:
y < 0.5

array([False, False, False, False,  True, False,  True, False, False,
        True, False, False, False, False,  True,  True,  True, False,
       False, False])

In [26]:
y[y < 0.5]

array([0.4236548 , 0.43758721, 0.38344152, 0.07103606, 0.0871293 ,
       0.0202184 ])

In [27]:
y[y >= 0.5]

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.64589411,
       0.891773  , 0.96366276, 0.79172504, 0.52889492, 0.56804456,
       0.92559664, 0.83261985, 0.77815675, 0.87001215])

In [28]:
np.where(y < 0.5, 0, 1)

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [29]:
np.where(y >= 0.5, 0, 1)

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0])

## iris

In [30]:
from sklearn.datasets import load_iris

iris = load_iris()

In [31]:
X = iris.data

In [32]:
type(X)

numpy.ndarray

In [33]:
X.shape

(150, 4)